### ISSUE TITLE
Support @enter?

### ISSUE THREAD

**Issue by tkf** [JuliaDebug/Infiltrator.jl#10]
Hi, this is a nice package.  I find it very useful, especially when combined with Debugger.jl so that I can do `Main.@enter some_function()` inside Infiltrator.jl REPL.  It would be nice if Infiltrator.jl can do this automatically and make `@enter` usable without `Main.` prefix. This also avoids the situation where you forgot to do `using Debugger` first in Julia REPL. I think you can just dynamically load Debugger.jl and avoid putting it as a dependency of Infiltrator.jl.

**Comment by KristofferC** [comment]
Personally, I think that `Debugger.jl` should support this package so you can just 

```
using Debugger
```

and put `@enter`s in your code and it would then have the same UI and commands as Debugger (`bt` for backtrace `` ` `` for evaluating Julia code, etc.

**Comment by pfitzseb** [comment]
Agreed. This package is more of a PoC than anything else, and I think its functionality will eventually be be directly available in Debugger.jl/Juno's Debugger (also ref https://github.com/JuliaDebug/Infiltrator.jl/issues/7 and https://github.com/JuliaDebug/Infiltrator.jl/pull/8).

Not entirely sure how much code re-use would make sense though, since there is basically *no* new functionality in Infiltrator apart from the `@infiltrate` macro -- everything else is scaffolding for the new REPL mode and stuff like that.

**Comment by KristofferC** [comment]
Yeah, I've been thinking about integrating it into Debugger but it might make sense to just copy the idea since the core idea here is what is important, not so much the implementation.

**Comment by pfitzseb** [comment]
Right, the only actually interesting code in Infiltrator is [this](https://github.com/JuliaDebug/Infiltrator.jl/blob/master/src/Infiltrator.jl#L59-L66). So far I haven't been able to figure out a good code sharing strategy for the different Debugger front-ends.

**Comment by tkf** [comment]
Thanks a lot for sharing future plans!  I'm looking forward to using this feature supported in Debugger.
