### ISSUE TITLE
Using assignments

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaDebug/Infiltrator.jl#22]
```
julia> f(x) = @infiltrate
f (generic function with 1 method)

julia> f(2)
Hit `@infiltrate` in f(::Int64) at REPL[3]:1:

debug> x
2

debug> y = x
2

debug> y
ERROR: UndefVarError: y not defined
```

**Comment by pfitzseb** [comment]
You can't introduce new local bindings right now, but globals work fine:
```
debug> @eval Main y=2
2

debug> y
2
```
I could probably make assignments into unresolved bindings evaluate into a scratch module automatically though...

**Comment by pdeffebach** [comment]
Would love to have this feature! I use R's `browse` a lot and each time you enter the fancy REPL there is a new environment to play around in. 

This should be feasible, right? You can just `@exfiltrate` to a temporary module remove that module when you exit the REPL?

**Comment by adriangb** [comment]
+1 on this functionality

In Python, I often set a breakpoint in a function that I get to via running tests in the debugger. This allows me to explore and write the fix in a REPL-like fashion then finalize it in the actual code/file. Currently, using infiltrator, I can explore but I cannot really use it as a REPL because you can't do assignments, define new functions, etc.
