### ISSUE TITLE
Command to Exit REPL and Terminate Running Program

### ISSUE THREAD

**Issue by jusevitch** [JuliaDebug/Infiltrator.jl#32]
When I debug, I frequently use multiple `@infiltrate` points. When I hit `Ctrl+D`, the REPL exits but then immediately appears again at the very next `@infiltrate` point. To exit the debugging session _and_ stop the currently running program, I currently have to use the `@stop` macro on every individual `@infiltrate` point and then hit `Ctrl+C` one last time to stop program execution. (The command `Ctrl+C` inside the Infiltrator REPL does not terminate the program on the default Ubuntu 20.04 terminal).

Is there a command where I can simultaneously stop all `@infiltrate` points and terminate the running program?

**Comment by jlchan** [comment]
I copied the approach of https://github.com/JuliaDebug/Infiltrator.jl/pull/6 and adding a toggle `const SKIP_ALL = Ref{Bool}(false)`, a `@skip_all` option which sets `SKIP_ALL=true`, and a second conditional similar to https://github.com/JuliaDebug/Infiltrator.jl/blob/08b24d39ae757170c3f9b607ec8c79eaf8466300/src/Infiltrator.jl#L91. 

This works, but users have to reset `SKIP_ALL=false` every time `@skip_all` is called inside the debugger. I'm not sure if there's a better way, since each `@infiltrate` statement is independent and the only way to skip them all seems to be a global toggle.

**Comment by jlchan** [comment]
I could make a PR if this sounds reasonable.

**Comment by jlchan** [comment]
Nevermind 😅
